### ISSUE TITLE
Fully formed Github repo urls leading to 400 error

### ISSUE THREAD

**Issue by fperez** [jupyter/nbviewer#835] opened 2019-06-12 07:00 UTC
When giving nbviewer a fully formed Github repo URL, say `https://github.com/jupyter-widgets/tutorial`, a 400 error results:

**To Reproduce**
1. Go to https://nbviewer.jupyter.org.
2. Paste into the input text box: `https://github.com/jupyter-widgets/tutorial`
3.  Nbviewer turns the above into `https://nbviewer.jupyter.org/urls/github.com/jupyter-widgets/tutorial` and produces a `400 : Bad Request` error.

**Expected behavior**
The repo should be rendered. That works as expected if instead one types only the org/repo part: `jupyter-widgets/tutorial`, leading to the URL `https://nbviewer.jupyter.org/github/jupyter-widgets/tutorial/tree/master/`.

I'm pretty sure this used to work, but I don't know when the change occured. Oddly this seems like it should be an often reported problem, but I couldn't find a dupe.

**Comment by parente** [comment] 2019-06-12 15:12
#832 was reported recently and is somewhat related. It appears to work for full GitHub URLs that resolve to ipynb files but perhaps not to the org/repo path alone.

**Comment by fperez** [comment] 2019-06-12 23:45
It's possible this is a corner case that didn't work in the past (I may be wrong above) but if it doesn't then I think it should - the combo of what works/doesn't in terms of URLs or bare repo names is odd and surprising.

I tagged it as such for now, assuming I'm wrong and it's not a regression.

**Comment by krinsman** [comment] 2019-07-05 19:25
This is fixed by https://github.com/jupyter/nbviewer/pull/841

If you want to test this locally, see the Docker image I made [here](https://github.com/krinsman/jupyterhub-deploy/tree/master/github_url_fix).

**Comment by krinsman** [comment] 2019-07-05 23:47
Oh OK I see what the problem is -- [the regex for the `GitHubRedirectHandler` by design only works for tree, blob, or raw URLs](https://github.com/jupyter/nbviewer/blob/124961fde02bfea783a09b8961a6c52a274b84cb/nbviewer/providers/github/handlers.py#L319), whereas the cases mentioned above correspond to `github.com` URLs which are neither tree nor raw nor blob. 

The current PR I have for fixing this is probably not an optional solution, since it involves a code change to the URL handler, whereas by design we want the URL handler to not have to know about the existence of other handlers -- the `GitHubRedirectHandler` is supposed to make that unnecessary. So a better PR would rewrite the code of the `GitHubRedirectHandler` to handle other GitHub URLs.

My impression is that GitHub URLs are sufficiently well-structured that it should in most cases be unnecessary to do anything more than redirect `urls/github.com/blahblah` to `github/blahblah`. That doesn't make it possible to distinguish corner cases like `https://github.com/marketplace` versus `https://github.com/krinsman`, for example, but I think those are probably safe to ignore since most people won't try to look at GitHub marketplace with NBViewer anyway, and throwing a 400 at them (since that is presumably what the GitHub API will throw at NBViewer) seems reasonable in those cases.

I'll rewrite the PR soon to reflect this.

**Comment by krinsman** [comment] 2019-07-06 01:15
Implemented better fix than the first one: 
https://github.com/jupyter/nbviewer/pull/841
This can still be tested using [the same Docker image as before](https://github.com/krinsman/jupyterhub-deploy/tree/master/github_url_fix).

**Closed** 2019-07-07 14:30 UTC
Labels: type:Enhancement
