### ISSUE TITLE
Probelm in rendering plotly

### ISSUE THREAD

**Issue by anthonymakela** [jupyter/nbviewer#806] opened 2018-12-04 13:02 UTC
It seems that there's a problem while trying to render plotly graphs. Here's a very quick example. (https://nbviewer.jupyter.org/gist/anthonymakela/225d9b2e38374b41dbb31e7f40f2e752).

Here's the bug specified (https://github.com/IRkernel/IRkernel/issues/541#issuecomment-444089607)

**Comment by takluyver** [comment] 2018-12-04 13:09
I think this is a symptom of https://github.com/jupyter/nbconvert/issues/129

**Comment by krinsman** [comment] 2019-11-21 22:26
@anthonymakela 
Can you check to see whether this still happens when running with NBConvert on the notebook?

This sounds like it might be an NBConvert error (the program NBViewer calls). Have you tried running `jupyter nbconvert --to html JavaScriptTest.ipynb`? 

It's also possible to open the notebook in classic Jupyter Notebook or JupyterLab, and clicking `Save As` -> `HTML` to run NBConvert to convert the notebook into HTML.

Is the output the same as from Jupyter notebook/NBViewer? See: https://nbconvert.readthedocs.io/en/latest/usage.html

It might make sense to open an issue with [NBConvert](https://github.com/jupyter/nbconvert) instead.

I will tentatively close this issue assuming that the problem is with NBConvert. Please let me know if it should be reopened!

**Closed by krinsman** 2019-11-21 22:26 UTC
Labels: tag:Upstream, type:Bug
