### ISSUE TITLE
error when rendering a notebook with Coconut kernel

### ISSUE THREAD

**Issue by dm-wyncode** [jupyter/nbviewer#783] opened 2018-07-21 15:39 UTC
**Describe the bug**

If a URL to a notebook with the Coconut kernel is used, an error is thrown.

I have an instance of nbviewer installed. Here is a link to the error: http://bit.ly/2NB6RgL

Here is a notebook with the Python3 kernel that works normally: http://bit.ly/2NuTKxt

The error:

```
400 : Bad Request
We couldn't render your notebook

Perhaps it is not valid JSON, or not the right URL.

If this should be a working notebook, please let us know.

The error was: (six 1.8.0 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.9.0'), {'prompt-toolkit'})
```

**To Reproduce**

1. Create a notebook with the [Coconut Kernel](http://coconut.readthedocs.io/en/latest/DOCS.html#ipython-jupyter-support)
2. Serve the notebook via HTTP
3. Try to view in nbviewer.

**Expected behavior**
Normal display of the Coconut notebook.

It renders correctly on GitHub: https://gist.github.com/dm-wyncode/7dce67aec0a921ead5662181655dc9dd

**Screenshots**

![](http://bit.ly/2Nzanb4)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 -  Version 67.0.3396.99 (Official Build) (64-bit)

**Additional context**

Commit 1daffa4cbf9eff4fab9a680a065e5af4077e2eb2 of nbviewer hosted on an instance of Dokku using a modified Dockerfile.

**Comment by parente** [comment] 2018-07-27 02:17
The same notebook renders OK on the public nbviewer instance: http://nbviewer.jupyter.org/url/bit.ly/2O78ymR

The error page suggests that the requirement `six>=1.9.0` for parse toolkit was not met by the `six 1.8.0` version installed in your nbivewer environment. I'm a little surprised to see this at runtime, but it's a hint.

**Comment by krinsman** [comment] 2020-02-04 19:24
@dm-wyncode I am tentatively closing this issue for now due to an inability to reproduce the issue. In particular, the link to the notebook in question seems to now be defunct. Please let us know if this issue should be reopened so that we can continue to work on it.

**Closed by krinsman** 2020-02-04 19:24 UTC
Labels: status:Needs Reproduction, type:Question
