### ISSUE TITLE
inconsistent rendering between nbviewer and local/github jupyter notebook

### ISSUE THREAD

**Issue by dingran** [jupyter/nbviewer#740] opened 2017-11-27 17:18 UTC
Here is an example

Link to jupyter notebook on github https://github.com/dingran/latex-ipynb/blob/master/latex-cheatsheet.ipynb

Link to nbviewer rendering 
https://nbviewer.jupyter.org/github/dingran/latex-ipynb/blob/master/latex-cheatsheet.ipynb

The problem occurred in matrix section at the bottom. Github was able to render it properly, while nbviewer is not.

Here is the markdown in the cell 

````
$X=
\begin{bmatrix}
    \boldsymbol x_1 \\
    \boldsymbol x_2 \\
    \vdots \\
    \boldsymbol x_m
\end{bmatrix} 
=
\begin{bmatrix}
    x_{11} & x_{12} & x_{13} & \dots  & x_{1d} \\
    x_{21} & x_{22} & x_{23} & \dots  & x_{2d} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{m1} & x_{m2} & x_{m3} & \dots  & x_{md}
\end{bmatrix}$
````

Here are the screenshots for github and nbviewer respectively

*Github*
![screen shot 2017-11-27 at 12 10 39 pm](https://user-images.githubusercontent.com/12864782/33279276-0aab2dda-d36c-11e7-87e3-8660da340aea.png)

*Nbviewer*
![screen shot 2017-11-27 at 12 10 33 pm](https://user-images.githubusercontent.com/12864782/33279277-0ab781f2-d36c-11e7-8e38-856049a6350d.png)

**Comment by danilobellini** [comment] 2017-12-03 00:27
It's an nbconvert issue: https://github.com/jupyter/nbconvert/issues/404

**Comment by parente** [comment] 2018-07-08 02:43
The notebook linked in the issue description seems to have been updated to workaround the bug. Here's a link to a gist that reproduces the original issue for the record: https://nbviewer.jupyter.org/gist/parente/27756236768e5451fb380116f93e7e89

**Comment by fepegar** [comment] 2019-08-09 09:48
What's the solution for this? I'm having trouble with this notebook as well: https://nbviewer.jupyter.org/github/fepegar/cmri-coursework-3/blob/master/notebooks/Problem-2.ipynb?flush_cache=true

**Comment by krinsman** [comment] 2019-11-21 22:29
@dingran 
Can you check to see whether this still happens when running with NBConvert on the notebook?

This sounds like it might be an NBConvert error (the program NBViewer calls). Have you tried running `jupyter nbconvert --to html JavaScriptTest.ipynb`? 

It's also possible to open the notebook in classic Jupyter Notebook or JupyterLab, and clicking `Save As` -> `HTML` to run NBConvert to convert the notebook into HTML.

Is the output the same as from Jupyter notebook/NBViewer? See: https://nbconvert.readthedocs.io/en/latest/usage.html

It might make sense to open an issue with [NBConvert](https://github.com/jupyter/nbconvert) instead.

I will tentatively close this issue assuming that the problem is with NBConvert. Please let me know if it should be reopened!

**Closed by krinsman** 2019-11-21 22:29 UTC
Labels: tag:Upstream, type:Bug
