### ISSUE TITLE
hello i got a peoblom with Chinese characters garbled 

### ISSUE THREAD

**Issue by uyplayer** [jupyter/nbviewer#825] opened 2019-04-16 02:37 UTC
**Describe the bug**
after i convert ipynb file to html  and put html in my host ,in web page Chinese characters garbled , i donot know what is wrong 

look here : 
myblog:
http://uyplayer.com/tensorflow-2-0-alpha-learning-note/

github address for jupyter ipynb file:
https://github.com/uyplayer/tf_learning_notice/blob/master/tensorflow.org/0.overview/overview.ipynb

i donot know why

**Comment by krinsman** [comment] 2019-07-05 21:33
Hi, this seems like it's an issue with [NBConvert](https://github.com/jupyter/nbconvert) not NBViewer, since NBConvert is what actually converts the ipynb files to HTML -- you might want to consider filing the issue with that project instead.

**Comment by krinsman** [comment] 2019-11-21 22:21
@uyplayer In classic notebook or JupyterLab you can click `Save As` -> `HTML` to have NBConvert convert the notebook to HTML -- if the same issue occurs that also happens with NBViewer, then the problem is with NBConvert.

You can also run `jupyter nbconvert --to html <name of notebook file>`, see here: https://nbconvert.readthedocs.io/en/latest/usage.html

I am tentatively closing this issue, assuming that the problem is with NBViewer. Please let me know if it should be reopened!

**Closed by krinsman** 2019-11-21 22:21 UTC
Labels: tag:Upstream, type:Bug
