### ISSUE TITLE
Equation auto-numbering totally messed up the notebook

### ISSUE THREAD

**Issue by lnshi** [jupyter/nbviewer#827] opened 2019-05-07 07:25 UTC
As one of my notebook here: https://nbviewer.jupyter.org/github/lnshi/ml-exercises/blob/master/ml_basics/rdm011_support_vector_machines/support_vector_machines.ipynb

Why ppl need these kind of pointless auto-generated equation numbers, why ppl even need these pointless features...

How to explicitly disable in my notebook?

**Comment by krinsman** [comment] 2019-07-05 21:31
This seems most likely an issue with how [NBConvert](https://github.com/jupyter/nbconvert) renders [MathJax](https://github.com/mathjax/MathJax). You might consider rendering the note using NBConvert:

    jupyter nbconvert --to html support_vector_machines.ipynb

If the output still looks incorrect from that, then the problem is with NBConvert of MathJax, not NBViewer, and you might want to consider filing issues with those projects instead.

**Comment by krinsman** [comment] 2019-11-21 22:18
@lnshi Did this help you? Were you able to open an issue with NBConvert?

You can also click `Save As` -> `HTML` in classic Jupyter Notebook or JupyterLab to convert the notebook to HTML using NBConvert.

I am tentatively closing this issue assuming that the problem is with NBConvert. Please let me know if it should be re-opened!

**Closed by krinsman** 2019-11-21 22:18 UTC
Labels: tag:Other Jupyter Project, tag:Upstream, type:Bug
