### ISSUE TITLE
Error 503 All backends failed or unhealthy

### ISSUE THREAD

**Issue by kubu4** [jupyter/nbviewer#607] opened 2016-04-27 23:19 UTC
Getting this error when trying to view notebooks:

Error 503 All backends failed or unhealthy

All backends failed or unhealthy
Guru Mediation:

Details: cache-sjc3134-SJC 1461798991 3919965035

Varnish cache server

**Comment by willingc** [comment] 2016-04-28 00:21
@rgbkrk @minrk Looks like the tmpnb-director needs some love. I don't have the passwords or I would reset.

@kubu4 Thanks for reporting the issue.

**Comment by rgbkrk** [comment] 2016-04-28 00:54
On it.

**Comment by jjehl** [comment] 2016-11-25 15:41
Getting the error. Seems to be a random issue.

**Comment by ischurov** [comment] 2016-11-26 20:06
The same thing here (Russia).

**Comment by willingc** [comment] 2016-11-27 18:20
@jjehl @ischurov Are you using http://try.jupyter.org or https://try.jupyter.org?

**Comment by willingc** [comment] 2016-11-29 13:45
@rgbkrk @minrk What needs to be reset to avoid the 503 error with http?

**Comment by ischurov** [comment] 2016-11-29 15:43
I was using nbviewer with http (like [this](http://nbviewer.jupyter.org/github/ischurov/pythonhse/blob/master/Lecture%203.ipynb#Проверка-условий)). As for now, https for the netioned work neither. See also my [comments](https://github.com/jupyter/nbviewer/issues/631#issuecomment-263082829) to issue #631 (seem to be the same or related issue). It does not depend on using github API as it can be reproduced with the notebook placed outside of github.

**Comment by willingc** [comment] 2016-11-30 11:14
Thanks @minrk. 

I'm going to close this issue. Resolution: The error occurs when Carina deployment is under heavy load. It resolves when the load decreases.

**Closed by willingc** 2016-11-30 11:14 UTC

**Comment by ischurov** [comment] 2016-11-30 11:57
@willingc what does it mean from the user's perspective? Can we still rely on nbviewer as a way to give links to our published notebooks in a readable way, or should we expect that these links become unaccessible from time to time like described in this and the related issues? For example, I used nbviewer together with Github to publish my lecture notes and liked that solution very much, but eventually I discovered that my students do not have access to these lecture notes. Personally, I resolved this issue for myself by installing nbviewer on my own server and pointing links there — it was surprisingly easy (thanks to Docker). I understand that nbviewer is a free service and there's no any guaranties, but if we do not expect that nbviewer is reliable, maybe it is better to warn the users clearly and point them to other solutions (like installing on own server)?

**Comment by willingc** [comment] 2016-11-30 12:36
Hi @ischurov,

You raise some good questions. Yes, we do expect nbviewer to be reliable for users. As a free service (graciously hosted by Rackspace), we do experience spikes in demand at times. I've opened a new issue https://github.com/jupyter/nbviewer/issues/645 to review the service load and capacity.

I'm glad that you are using Jupyter with your lecture notes and teaching. A Docker instance as you mention is a good option for those that are using nbviewer regularly for teaching. It's a great suggestion to improve documentation and raise user awareness of self hosting. I've added a new issue to address your suggestion https://github.com/jupyter/nbviewer/issues/646.

Please feel free to ping us here on GitHub or the mailing list if you continue to experience issues. Thanks!

**Comment by jjehl** [comment] 2016-12-01 08:54
Thanks for your explanations. I'm also using nbviewer for teaching and if the service is not reliable I'm going to instal my own server like @ischurov  . Anyway, it is a good news for you to have heavy load, means your service is well appreciated !

**Comment by medellinfein** [comment] 2016-12-13 19:09
This issue seems to have gone from bad to worst. Basically, it is impossible to use the notebooks right now since one receives this error no less than 80% of the time _irrespective of time of day_.

Is there a way to monitor the load on the whichever service is responsible for deploying the notebook?(Carina?)

**Comment by willingc** [comment] 2016-12-13 19:20
@rgbkrk @minrk If either of you are around, would you mind taking a look at the logs. Thanks!

**Comment by mkempenaar** [comment] 2016-12-13 19:30
Experiencing this too for the last few weeks and I am - was? - relying on nbviewer for lecture material.

If there is any way for the community to give support to get extra resources, please let us know.

**Comment by jjehl** [comment] 2016-12-14 08:28
At the moment, it work for me in France.  I find this service useful and  just donated some money to support your project (http://jupyter.org/donate.html). Maybe it can help you ti improve your service ;-)

**Comment by minrk** [comment] 2016-12-14 09:38
I've just moved nbviewer to a traditional server, which should improve things. Carina was stable for a long time, but is going through a transition that appears to be causing disruptions. I've pulled nbviewer off of it for now.

**Comment by willingc** [comment] 2016-12-14 14:28
Thanks @jjehl for the donation :heart: 

Thanks @minrk 👍

**Comment by minrk** [comment] 2016-12-14 14:41
Thank you very much for the donation! We shall do our best to earn it. I'm working on some better instrumentation for nbviewer's status that should show up on our status page: http://status.jupyter.org
