### ISSUE TITLE
nbviewer URLs when transfering Github repos

### ISSUE THREAD

**Issue by chdoig** [jupyter/nbviewer#324] opened 2014-08-13 20:35 UTC
When transferring Github repos https://help.github.com/articles/how-to-transfer-a-repository:

> all links to the previous location are automatically redirected to the new location.

Github returns 301 code on transferred repository, but notebooks URLs in nbviewer won't get redirected.

It would be nice to have an automatic redirection in nbviewer too, to avoid changing the URLs manually.

cc @damianavila

**Comment by krinsman** [comment] 2019-07-05 23:30
It seems like the [GitHub API as of version 3](https://developer.github.com/v3/#http-redirects) is already doing all of the hard work of this for us already. In particular, if one looks at [this example of a redirected repository from the GitHub team](https://gist.github.com/jasonrudolph/56388a4ff51b4f721cac), we can see that NBViewer is automatically redirected to the correct repository.

More specifically, `jasonrudolph/jasonrudolph.com` redirects to `jasonrudolph/jasonrudolph.github.io`, and NBViewer returns the same tree view for both username/repo combinations, as it should:

Compare:
https://nbviewer.jupyter.org/github/jasonrudolph/jasonrudolph.com/tree/master
with:
https://nbviewer.jupyter.org/github/jasonrudolph/jasonrudolph.github.io/tree/master/

The only difference is that the breadcrumbs for the first one is incorrect -- it says `jasonrudolph.com` even though the API redirected to `jasonrudolph.github.io`. That makes sense since the [`GitHubTreeHandler` only uses the initial parameters of the original GET request to determine the repo name](https://github.com/jupyter/nbviewer/blob/124961fde02bfea783a09b8961a6c52a274b84cb/nbviewer/providers/github/handlers.py#L166), not accounting for the possibility that the API has responded with the contents of a redirected repository. The API documentation says that the name of the redirected repo [should be located in the `Location` header field](https://developer.github.com/v3/#http-redirects). However, the Tornado HTTP client [allows redirects by default](https://www.tornadoweb.org/en/stable/httpclient.html#tornado.httpclient.HTTPRequest) since the default value for `follow_redirects` is `True`. But we would only get to see the Location header if we weren't automatically following redirects (but we are), i.e. if the Tornado HTTP client were throwing an error when getting a 301 response rather than following the redirect. This can be confirmed by modifying  [this line](https://github.com/jupyter/nbviewer/blob/124961fde02bfea783a09b8961a6c52a274b84cb/nbviewer/providers/github/handlers.py#L134) to have the additional argument `follow_redirects=False` and adding `app_log.info(exc.response.headers)` [here](https://github.com/jupyter/nbviewer/blob/master/nbviewer/providers/base.py#L364) to allow us to look at the error-throwing response's headers before NBViewer errors out itself.

One can also add `app_log.info("response.effective_url: %s", response.effective_url)` [here](https://github.com/jupyter/nbviewer/blob/124961fde02bfea783a09b8961a6c52a274b84cb/nbviewer/providers/github/handlers.py#L135) to verify indeed that ultimately GitHub is sending us the information from the redirected repository. Doing this for `jasonrudolph/jasonrudolph.com`, we get that: `response.effective_url: https://api.github.com/repositories/208480/contents/?ref=master`. [Looking at the response in a web browser](https://api.github.com/repositories/208480/contents/?ref=master), we can see that all of the files are actually from the repo `jasonrudolph/jasonrudolph.github.io`.

It seems that redirected repos are assigned an arbitrary number and listed under `repositories/arbitrary_number`, since the `effective_url` for `jasonrudolph/jasonrudolph.github.io` is `response.effective_url: https://api.github.com/repos/jasonrudolph/jasonrudolph.github.io/contents/?ref=master`. (Note the change from `repositories` for the redirect+number vs `repos` for no redirect.) But anyway as one can verify with a diff checker or looking the browser, the [second JSON](https://api.github.com/repos/jasonrudolph/jasonrudolph.github.io/contents/?ref=master) is identical to the first.

**Comment by krinsman** [comment] 2019-07-06 00:23
Fixed by https://github.com/jupyter/nbviewer/pull/841

**Closed** 2019-07-07 14:30 UTC
Labels: tag:Provider, type:Enhancement
