### ISSUE TITLE
Equations not rendered properly in new github ipython notebook automatic viewer

### ISSUE THREAD

**Issue by gregnordin** [jupyter/nbviewer#452] opened 2015-05-08 20:33 UTC
I am delighted that github will now render jupyter notebooks. Thanks to everyone who made this possible!!

In the spirit of finding and fixing bugs, I just want to let you know that I've run into a problem with latex equations rendered in a notebook in Firefox 37.0.2 on Mac OS X 10.9.4. You can see an example here: https://github.com/gregnordin/teststuff/blob/master/miscquicktests/ipython_eqn_numbers/150420_first_try_eqn_numbers.ipynb

The problem is that the equations are exceptionally small, and often malformed and misplaced on the page. Please note there is nothing polished about this notebook. I've just been using it as a place to try out different things with equation numbering and found it has a problem being rendered automatically on github so thought I'd pass this along.

Interestingly, the problem does not occur in Safari 7.0.6

**Comment by rgbkrk** [comment] 2015-05-08 20:51
Hey @gregnordin! For support issues with GitHub's rendering, email support@github.com.

For the time being, you can also paste the link to the notebook from github.com into nbviewer.ipython.org. However, it appears that they're the same size on the notebook viewer.

How does this compare to the running notebook server or when using the HTML output of `ipython nbconvert eqn_numbers.ipynb --to-html`?

**Comment by Carreau** [comment] 2015-05-08 21:03
Ouch, yes it is small indeed,
Maybe we should leave this open until it is fixed by github still.
(I'll repopen at their might be things to fix on our side too for github rendering to be able to work.)

**Comment by Carreau** [comment] 2015-05-08 21:03
For archive : 
![capture d ecran 2015-05-08 a 14 03 19](https://cloud.githubusercontent.com/assets/335567/7545579/03ef97cc-f58b-11e4-9c0c-b60e4f34936a.png)

**Comment by rgbkrk** [comment] 2015-05-08 21:05
Whoa, am I on a different browser than you two?

![screenshot 2015-05-08 16 05 22](https://cloud.githubusercontent.com/assets/836375/7545613/0927873e-f59c-11e4-870c-0db108cb64e8.png)

I'm on Chrome on OS X.

**Comment by Carreau** [comment] 2015-05-08 21:07
Yep, OP said Firefox, So I tried Firefox. Chrome is fine.

**Comment by rgbkrk** [comment] 2015-05-08 21:08
What a bad reader I am.

**Comment by Carreau** [comment] 2015-05-08 21:17
That's why you are paid to write software and not read software.

**Comment by gregnordin** [comment] 2015-05-08 21:48
@rgbkrk, no problem :) 

Here is some further information:

1. The notebook seems to render properly in nbviewer.ipython.org on both Firefox and Safari.
2. I posted the html output file to github (https://github.com/gregnordin/teststuff/blob/master/miscquicktests/ipython_eqn_numbers/150420_first_try_eqn_numbers.html) and it renders just fine when opened in both Firefox and Safari.
3. I also emailed support@github.com to alert them to the problem.

**Comment by cprybol** [comment] 2015-05-22 19:25
On chrome for OSX I've also seen these strange hanging lines when rendering a block of latex wrapped in double dollar signs, $$ {latex} $$.

inline single dollar sign $ {latex} $ renders fine

![screenshot 2015-05-22 15 19 58](https://cloud.githubusercontent.com/assets/3497642/7778076/1096b706-0096-11e5-891c-aab9410212f6.png)

**Comment by jwjohnson314** [comment] 2015-06-18 19:58
I have a related issue: inline equations not showing up, and an 'undefined control sequence error'. An example is here: https://github.com/jwjohnson314/Differential-Equations/blob/master/Direction%20Fields.ipynb

**Comment by bollwyvl** [comment] 2015-06-18 21:29
All looks good on latest chrome, win7 as well as this screeshotbot
<https://api.url2png.com/v6/P4DF2F8BC83648/49fc330faf2a31c55e54baba9c7404a6/png/?thumbnail_max_width=851&url=https%3A%2F%2Fgithub.com%2Fjwjohnson314%2FDifferential-Equations%2Fblob%2Fmaster%2FDirection%2520Fields.ipynb&viewport=1280x2000>,
which likely uses webkit.

Firefox, on the other hand, looks like some creepypasta.

What browser are you using?

**Comment by jwjohnson314** [comment] 2015-06-18 21:38
I figured out a fix. The problem is that the LaTeX command \dfrac isn't recognized. I'm not sure why that would be, but anyway, shortly after I commented above, I replaced occurrences of \dfrac with \frac and it rendered fine. Thanks!

**Comment by peterroelants** [comment] 2015-06-22 07:39
I have the same issue when loading [this page](https://github.com/peterroelants/peterroelants.github.io/blob/master/notebooks/neural_net_implementation/neural_network_implementation_part01.ipynb). And I only use ' \frac', not '\dfrac' All goes well when using Chrome or Safari, but Firefox (version 33.1.1) has the follosing rendering as a result: 
![Firefox error](http://i.imgur.com/WdeGy4s.png) 


[Nbviewer](http://nbviewer.ipython.org/) has this correct rendering as a result. So it is a Github specific issue: 
![correct rendering](http://i.imgur.com/USUBSJG.png) 


I don't have internet explorer installed, but someone send me a screenshot of a related rendering in IE11 that looks like this: 
![IE 11](http://i.imgur.com/A3AwXrh.png?1)


It was noted in [this blog post](http://blog.jupyter.org/2015/05/07/rendering-notebooks-on-github/) that "bugs with notebook rendering on GitHub or nbviewer" should be filed on the nbviewer repo. So I added it to this related issue.

**Comment by fedorn** [comment] 2015-07-15 21:10
There is the same issue with Firefox on Linux.
Are there any workarounds for this? Unfortunately, I can't use nbviewer.ipython.org because my repo is private now.

**Comment by robert-dodier** [comment] 2015-08-07 23:46
For the record, I've bumped into the same problem (i.e. LaTeX equations in notebooks are displayed very very small). I am using Firefox 39 on Linux. 

Here is an example of a notebook which is rendered incorrectly by the Github notebook renderer: https://github.com/robert-dodier/maxima-fishbowl/blob/master/MaximaFishbowlExample.ipynb

Here is the same notebook rendered correctly by nbviewer.ipython.org: http://nbviewer.ipython.org/github/robert-dodier/maxima-fishbowl/blob/master/MaximaFishbowlExample.ipynb

If anybody figures out a work around, I'd be interested to hear about it.

**Comment by tscheff** [comment] 2015-08-13 09:59
Same problem here: https://github.com/tscheff/Test/blob/master/Test%20Sheet.ipynb

Equations too small on Firefox 40.0, but ok in Safari 8.0.7 (both OS X 10.10.4)

**Comment by singletS** [comment] 2015-09-19 14:52
Here's another "me-too" using the recent firefox release.

I'm seeing the femto-font problem using firefox 40.0.3 linux rendered by github. All fractions use only \frac{}.

As others mentioned, mathjax equations look fine on nbviewer.org, using the same firefox with a local jupyter install, or using chromium (works even on github-rendered notebooks). Seems limited to ff-github interactions. Is it better nag support@github.com? Do we know the nature of the problem? Thanks...

**Comment by moorepants** [comment] 2015-12-02 18:39
Bad on Firefox 42.0 on Ubuntu 15.10 for me:

https://gist.github.com/moorepants/aa3ab251acf6ae357084

**Comment by sefffal** [comment] 2016-01-12 23:12
Similarly garbled in MS Edge, on Win 10.
Renders fine running notebook locally, garbled when viewing on Github in edge. Works fine in chrome.

**Comment by willingc** [comment] 2016-01-13 01:37
@sefffal Thanks for the report on Edge.

**Comment by benrbray** [comment] 2016-01-31 17:54
+1, this happens to me on Ubuntu 14.04 with both Firefox 44.0 and Chrome 48.0.2564.97 (64-bit).  Strangely, MathJax in Firefox is too small, while in Chrome it's squeezed into a thin box and vertical lines appear:

Firefox:

![image](https://cloud.githubusercontent.com/assets/221963/12703782/49f69ba6-c819-11e5-8f77-d8dddfdb5482.png)

Chrome:

![image](https://cloud.githubusercontent.com/assets/221963/12703788/61b3f586-c819-11e5-9fb6-0c7b2a70243e.png)

Here is the notebook in question, both on [GitHub](https://github.com/rszeto/umich-eecs545-lectures/blob/master/lecture05_linear-regression-part2/lecture05_final_linear-regression-part-2.ipynb) and [nbviewer](http://nbviewer.jupyter.org/github/rszeto/umich-eecs545-lectures/blob/master/lecture05_linear-regression-part2/lecture05_final_linear-regression-part-2.ipynb).

**Comment by TobbeTripitaka** [comment] 2016-02-22 08:31
Any update on this problem? I experience the same on Firefox 44.0.2.

**Comment by JPinSPACE** [comment] 2016-03-24 14:09
Add another to the list of people experiencing this problem. All LaTeX equations are extremely small in Firefox, both on OSX and Windows 7.

**Comment by willingc** [comment] 2016-03-24 14:30
@JPinSPACE If you prefix and postfix your LaTeX source with a $, does it display correctly for you in Firefox? See https://github.com/jupyter/notebook/blob/master/docs/source/examples/Notebook/Typesetting%20Equations.ipynb

```
$\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}$
```

Certainly not a long term fix @JPinSPACE. Just something that I noticed that helps in some cases.

**Comment by JPinSPACE** [comment] 2016-03-24 14:39
@willingc afraid not! Here's an example of some latex I put in a markdown cell: `$R = R_e = 6378.14\ km$`. In Chrome that looks fine but in Firefox the equation is only a few pixels tall.

**Comment by willingc** [comment] 2016-03-24 14:44
@JPinSPACE Thanks for checking. Sorry it didn't work in your use case.

Hopefully, someone else will chime in if they have a more robust workaround or fix.

**Comment by thomas-haslwanter** [comment] 2016-04-20 07:53
I have the same problem!

**Comment by anzelpwj** [comment] 2016-04-28 19:13
It's bad with Chrome in MacOS. I'm seeing much the same as benrbray.

**Comment by toogy** [comment] 2016-06-01 12:02
Same problem on latest version of Firefox

**Comment by pilipolio** [comment] 2016-07-28 10:26
Same problem (tiny equations) of MacOS with firefox 47.0, and on Chrome 51.xxx I have every latex line ending by a '|' plus some weird line returns.

**Comment by aakhmetz** [comment] 2016-07-28 10:27
Safari works well for that

**Comment by aakhmetz** [comment] 2016-10-03 03:19
Yesterday, I updated my Mathjax to the latest version 2.6 and all looks fine in Firefox (version 49.0)

**Comment by moorepants** [comment] 2016-10-03 04:35
Firefox 49 on Ubuntu 16.04 seems to work now for me too:

![selection_040](https://cloud.githubusercontent.com/assets/276007/19027730/1604ffbe-88e8-11e6-9ddb-d3ee09ff561d.jpg)

**Comment by willingc** [comment] 2016-10-03 05:06
Thanks @moorepants and @aakhmetz for the updates. Very glad it is working for you on Firefox 49.

I'm going to go ahead and close this issue.
**Resolution: Using Firefox 49 with MathJax now renders correctly.**

**Closed by willingc** 2016-10-03 05:06 UTC
Labels: github

**Comment by tgy** [comment] 2016-10-03 07:52
I confirm it now works for me :smiley:

**Comment by robert-dodier** [comment] 2017-06-30 17:26
Github nbviewer works better now, but still a little odd, in particular with ratios. I'm working with Firefox 50.1.0.

Attached file ![github-nbviewer-example-2017-06-30](https://user-images.githubusercontent.com/1489136/27747009-57d75728-5d7e-11e7-9300-f16915925563.png) is what I am seeing when I view a notebook in the Github nbviewer.
That image was captured from: https://github.com/robert-dodier/maxima-jupyter/blob/master/MaximaJupyterExample.ipynb

Attached file ![jupyter-nbviewer-example-2017-06-30](https://user-images.githubusercontent.com/1489136/27747008-57cf2026-5d7e-11e7-8c08-ad69ca8d8568.png) is what I am seeing when I view a notebook in the Jupyter nbviewer.
That image was captured from: http://nbviewer.jupyter.org/github/robert-dodier/maxima-jupyter/blob/master/MaximaJupyterExample.ipynb

I think the denominators in ratios look strangely small in the Github nbviewer. Not a big deal, it's tolerable, but I don't think that's an accurate version of what it would look like if rendered by LaTeX.
