### ISSUE TITLE
Vector magnitude notation $\|$ cannot be rendered in markdown table. 

### ISSUE THREAD

**Issue by HI-01** [jupyter/nbviewer#813] opened 2019-01-03 11:55 UTC
Hi! Thanks for using Jupyter Notebook Viewer (nbviewer) and taking the time to report a bug you've encountered. Please use the template below to tell us about the problem.

If you've found a bug in a different Jupyter project (e.g., [Jupyter Notebook](http://github.com/jupyter/notebook), [JupyterLab](http://github.com/jupyterlab/jupyterlab), [JupyterHub](http://github.com/jupyterhub/jupyterhub), etc.), please open an issue using that project's issue tracker instead.

If you need help using or installing Jupyter Notebook Viewer, please use the [jupyter/help](https://github.com/jupyter/help) issue tracker instead.

**Describe the bug**
The vector magnitude notation `$\|$` cannot be rendered correctly in a table using markdown. 

**To Reproduce**
1. Go to '[OrbitSimulation - Github](https://github.com/HI-01/OrbitSimulation/blob/master/Orbital%20Simulation.ipynb)' or '[OrbitSimulation - nbviewer](https://nbviewer.jupyter.org/github/HI-01/OrbitSimulation/blob/717fd81642d0881617d5d61243e33ea38c2e18cf/Orbital%20Simulation.ipynb)'
2. Scroll down to 'Rocket Variables' (the very end of the project)
4. See error: notation displayed incorrectly

**Expected behavior**
Render of the vector magnitude notation "double vertical lines". ||v||
Desired render example from jupyter notebook:
![Figure 1](https://user-images.githubusercontent.com/28213746/50636197-2e6b4500-0f90-11e9-87da-1555e71c0f68.png)

**Screenshots**
Undesired render from nbviewer:
![default](https://user-images.githubusercontent.com/28213746/50636414-f0baec00-0f90-11e9-98e6-e7bdb822400c.png)
Undesired render from Github:
![default](https://user-images.githubusercontent.com/28213746/50636305-85711a00-0f90-11e9-8562-0e3f53356caa.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 1803]
 - Browser [Firefox; Chrome]
 - Version [64.0; 66.0.3359.139]

**Smartphone (please complete the following information):**
 - Not applicable
 - Device: [e.g.]
 - OS: [e.g.]
 - Browser [e.g. ]
 - Version [e.g.]

**Additional context**

Thank you.

**Comment by krinsman** [comment] 2019-11-21 22:25
@HI-01 
Can you check to see whether this still happens when running with NBConvert on the notebook?

This sounds like it might be an NBConvert error (the program NBViewer calls). Have you tried running `jupyter nbconvert --to html JavaScriptTest.ipynb`? 

It's also possible to open the notebook in classic Jupyter Notebook or JupyterLab, and clicking `Save As` -> `HTML` to run NBConvert to convert the notebook into HTML.

Is the output the same as from Jupyter notebook/NBViewer? See: https://nbconvert.readthedocs.io/en/latest/usage.html

It might make sense to open an issue with [NBConvert](https://github.com/jupyter/nbconvert) instead.



I will tentatively close this issue assuming that the problem is with NBConvert. Please let me know if it should be reopened!

**Comment by krinsman** [comment] 2020-02-04 19:21
I am closing this tentatively for now as more likely to be an issue with NBConvert than with NBViewer. Please let me know @HI-01 if you have went through the above steps and confirmed that the issue is not with NBConvert, so we can reopen this issue.

**Closed by krinsman** 2020-02-04 19:21 UTC
Labels: tag:Upstream, type:Bug
