### ISSUE TITLE
pyLDAvis not found

### ISSUE THREAD

**Issue by DigiTransGlasgow** [jupyter/nbviewer#796] opened 2018-09-20 11:58 UTC
Hello, I cannot run my visualisation on nbviewer/GitHub. It all runs great on my local jupyter notebook:

`import pyLDAvis`

returns this error:

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-92fbba479eb0> in <module>()
----> 1 import pyLDAvis
      2 import pyLDAvis.sklearn
      3 pyLDAvis.enable_notebook()

ModuleNotFoundError: No module named 'pyLDAvis'

```

and the graphic is not displayed. What am I doing wrong?

**Comment by parente** [comment] 2018-12-30 20:40
Correct me if I'm wrong, but I think you're talking about running a notebook on mybinder.org.

NBViewer provides a link to launch a Jupyter Notebook server on mybinder.org. Binder bundles up the contents of the git repo containing the notebook you are viewing, but doesn't automatically figure out all of its dependencies. The git repo containing the notebook needs to declare the packages the notebook needs to run [in a way that Binder understands](https://mybinder.readthedocs.io/en/latest/using.html#preparing-a-repository-for-binder). You can try filing an issue in the repo containing the notebook, or, better yet, submitting a pull request to the repo to make it reproducible with Binder.

**Comment by krinsman** [comment] 2020-02-04 19:22
@DigiTransGlasgow Was this response useful for you?

I am tentatively closing this issue for now, under the assumption that the problem is likely to be with Binder or pyLDAvis. Please let me know if you have verified that this is not the case so we can reopen the issue.

**Closed by krinsman** 2020-02-04 19:22 UTC
Labels: tag:Other Jupyter Project, type:Question
