### ISSUE TITLE
Slide show fails to render; yet another data point

### ISSUE THREAD

**Issue by ben-albrecht** [jupyter/nbviewer#476] opened 2015-07-09 13:24 UTC
I tried to render my slides from here: 
https://github.com/ben-albrecht/PythonWorkshop2015/blob/master/PythonBootCamp/slideshow.ipynb

using:
http://nbviewer.ipython.org/format/slides/github/ben-albrecht/PythonWorkshop2015/blob/master/PythonBootCamp/slideshow.ipynb

and get:

    400 : Bad Request
    We couldn't render your notebook

    Perhaps it is not valid JSON, or not the right URL.

    If this should be a working notebook, please let us know.

    The error was: slideshow

The notebook converts to slides fine locally (I already presented them) using:

    ipython nbconvert slideshow.ipynb --to slides --post serve

Also, the slides render fine as just a regular notebook:
http://nbviewer.ipython.org/github/ben-albrecht/PythonWorkshop2015/blob/master/PythonBootCamp/slideshow.ipynb

**Comment by bollwyvl** [comment] 2015-07-09 13:32
Looks like another #466. As mentioned there, the nickle fix is to just manually go through and toggle all of your `Slide Type: -` slides to something else and back.

This is been fixed in the [upstream](https://github.com/ipython/ipython/pull/8415), so we're really just waiting for a deployment. We've got rather a debt vs master building up here... @rgbkrk?

**Comment by ben-albrecht** [comment] 2015-07-09 13:52
Excellent - thank you, I didn't see #466 earlier. 

There was one `-` slide_type I missed. Fixed it, and now it works fine as demonstrated here:
http://nbviewer.ipython.org/format/slides/github/ben-albrecht/PythonWorkshop2015/blob/master/PythonBootCamp/slideshow.ipynb#/1

**Comment by rgbkrk** [comment] 2015-07-11 03:24
It seems like we're only one commit behind, but it also depends on Fastly's cache for what you see for a commit on the page.

**Comment by jorisvandenbossche** [comment] 2015-08-29 22:59
Any progress on this front? I also encountered the issue today.

**Comment by bollwyvl** [comment] 2015-08-30 00:31
With #493 merged, we will be working off nbconvert proper, not the
backports to ipython 3.x... and I believe this has been fixed there. Stay
tuned!

**Comment by bollwyvl** [comment] 2015-08-30 03:03
Just verified that the minimal test case on #466 will be fixed once this is deployed.

**Comment by bollwyvl** [comment] 2015-09-01 00:32
Fixed in production! Please open additional issues if you experience more problems!

**Closed by bollwyvl** 2015-09-01 00:32 UTC
Labels: upstream

**Comment by jorisvandenbossche** [comment] 2015-09-01 07:11
I can confirm that it works for the ones I was looking at. Thanks!

**Comment by bollwyvl** [comment] 2015-09-01 11:53
Great!
