### ISSUE TITLE
Error 503: GitHub API rate limit exceeded. Try again soon.

### ISSUE THREAD

**Issue by cornhundred** [jupyter/nbviewer#673] opened 2017-02-22 15:50 UTC
I am getting this error on a few notebooks, but I can't imagine that I have reached any traffic limits

[http://nbviewer.jupyter.org/github/MaayanLab/single_cell_RNAseq_Visualization/blob/master/Single%20Cell%20RNAseq%20Visualization%20Example.ipynb](http://nbviewer.jupyter.org/github/MaayanLab/single_cell_RNAseq_Visualization/blob/master/Single%20Cell%20RNAseq%20Visualization%20Example.ipynb)

[https://nbviewer.jupyter.org/github/MaayanLab/clustergrammer-widget/blob/master/DataFrame_Example.ipynb](https://nbviewer.jupyter.org/github/MaayanLab/clustergrammer-widget/blob/master/DataFrame_Example.ipynb)

It also seems to be a general issue with nbviewer since I can't reach this notebook also (linked from the front page)

[http://nbviewer.jupyter.org/github/ipython/ipython/blob/4.0.x/examples/IPython%20Kernel/Cell%20Magics.ipynb](http://nbviewer.jupyter.org/github/ipython/ipython/blob/4.0.x/examples/IPython%20Kernel/Cell%20Magics.ipynb)

**Comment by cornhundred** [comment] 2017-02-22 16:02
It seems to be back up. I noticed the same error earlier in the week, but it doesn't seem to last long.

**Comment by minrk** [comment] 2017-02-22 16:28
@cornhundred it's not you, it's nbviewer itself that's hitting GitHub too much. When a lot of people are using it, we run out of API requests. #674 should improve the behavior when the rate limit is hit by reusing cached values if available.

**Comment by minrk** [comment] 2017-02-22 16:44
I just deployed the new version, but it will be a bit before it propagates.

**Comment by minrk** [comment] 2017-02-23 10:59
The API exhaustion seems to have been caused primarily by an ill-behaved bot. I've blocked the bot for now, and will explore our own rate limiting in the future.

**Comment by minrk** [comment] 2017-02-23 15:01
Rate limiting in #675

**Comment by minrk** [comment] 2017-02-27 12:30
Rate limit available hasn't dropped below 80% since the update, I think we can close this.

**Closed by minrk** 2017-02-27 12:30 UTC

**Comment by xiaohk** [comment] 2019-05-23 15:36
I am getting the same error for my [notebooks](https://nbviewer.jupyter.org/github/gitter-lab/t-cell-classification/blob/master/image_processing.ipynb).

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/15007159/58266074-94d9df80-7d46-11e9-97a3-6166a743cd9a.png">

**Comment by cornhundred** [comment] 2019-10-07 15:48
I'm seeing this error again with this link 

https://nbviewer.jupyter.org/github/giannarelli-lab/Single-Cell-Immune-Profiling-of-Atherosclerotic-Plaques/blob/master/notebooks/1.1_CITE-seq_GEX_PBMC_and_Plaque.ipynb

but not this link 

https://nbviewer.jupyter.org/github/giannarelli-lab/Single-Cell-Immune-Profiling-of-Atherosclerotic-Plaques/blob/master/notebooks/1.0_CITE-seq_ADT_PBMC_and_Plaque.ipynb?flush_cache=true

**Comment by krinsman** [comment] 2019-10-07 17:36
Both links work now for me.

This is expected behavior, not a bug. The GitHub API only allows a user (in this case Project Jupyter) to make so many requests within any given hour.

**Comment by cornhundred** [comment] 2019-10-07 17:37
@krinsman thanks!

**Comment by BrainAnnex** [comment] 2025-06-07 02:35
There seem to be 2 threads about this...

This problem has been rather severe lately.  I guess some user/bot is abusing the https://nbviewer.org web service...  Waiting several minutes does nothing; it completely obliterates the use of the service!   It seems to especially happen after hours (PST hours, that is.)

Maybe future versions of the nbviewer.org web service could monitor IP's of the requesters, and block abusers - to avoid running afoul, for an extended period!, of the GitHub rate limit?
