### ISSUE TITLE
The error was: Failed to connect to localhost port 8988: Connection refused

### ISSUE THREAD

**Issue by Mespn520** [jupyter/nbviewer#895] opened 2020-02-04 20:31 UTC
Hi! Thanks for using Jupyter Notebook Viewer (nbviewer) and taking the time to report a bug you've encountered. Please use the template below to tell us about the problem.

If you've found a bug in a different Jupyter project (e.g., [Jupyter Notebook](http://github.com/jupyter/notebook), [JupyterLab](http://github.com/jupyterlab/jupyterlab), [JupyterHub](http://github.com/jupyterhub/jupyterhub), etc.), please open an issue using that project's issue tracker instead.

If you need help using or installing Jupyter Notebook Viewer, please use the [jupyter/help](https://github.com/jupyter/help) issue tracker instead.

**Describe the bug**
Should be a working notebook however the error that is stated in the title shows up

**To Reproduce**
Copy URL and paste into nbviewer

**Expected behavior**
Should see the notebook

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version Not sure

**Additional context**

**Comment by krinsman** [comment] 2020-02-04 22:00
Hi there @Mespn520 , thank you for contributing to NBViewer!

Can you clarify whether this occurred while viewing `nbviewer.jupyter.org`, or whether you were running a local instance of NBViewer?

If you were running a local instance of NBViewer, what command did you use to start the server?

It seems like the error in the issue title might have come from a Python stack trace. If so, could you please post the entire stack trace?

It also seems like you were trying to run/open NBViewer on a non-standard port, did you run NBViewer with the `--port` flag, e.g.

`python -m nbviewer --port=8988`?

If you did not, NBViewer would have been running on another port (i.e. besides 8988), and that would be why the connection was refused when you tried to connect to 8988.

Also, were you running NBViewer as a JupyterHub service? This would also be relevant.
Were you trying to run NBViewer from within a Docker container? If so, that would also be relevant.

**Comment by JustinJIn1997** [comment] 2020-03-03 10:30
At the command prompt, enter:
pip3 install ipywidgets
jupyter nbextension enable --py widgetsnbextension


then you will solve this issue

**Comment by krinsman** [comment] 2020-03-03 17:35
@JustinJIn1997 To clarify, you had the same issue as the original poster, and this was the solution that fixed the issue?

I am confused about whether these two issues are related.

**Comment by JustinJIn1997** [comment] 2020-03-04 00:01
sorry，bro。Mine was used to solve the issue of connection failed，so that you can create a new python3 file.I will delete this commant and answer in the first issue of jupyter notebook connect failed issue。Thanks for correcting my mistake.------------------ 原始邮件 ------------------
发件人: "krinsman"<notifications@github.com>
发送时间: 2020年3月4日(星期三) 凌晨1:35
收件人: "jupyter/nbviewer"<nbviewer@noreply.github.com>;
抄送: "JustinJIn1997"<2195436565@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [jupyter/nbviewer] The error was: Failed to connect to localhostport 8988: Connection refused (#895)



@JustinJIn1997 To clarify, you had the same issue as the original poster, and this was the solution that fixed the issue?
 
I am confused about whether these two issues are related.
 
&mdash;

**Comment by krinsman** [comment] 2020-03-04 02:14
Hi @Mespn520 I'm unable to reproduce this error, so I am provisionally closing this issue. If you tried the suggestion I gave above, and it still didn't work, please let me know, and I can reopen the issue.

**Closed by krinsman** 2020-03-04 02:14 UTC

**Comment by JustinJIn1997** [comment] 2020-03-04 02:34
ok I will------------------ 原始邮件 ------------------
发件人: "krinsman"<notifications@github.com>
发送时间: 2020年3月4日(星期三) 上午10:14
收件人: "jupyter/nbviewer"<nbviewer@noreply.github.com>;
抄送: "JustinJIn1997"<2195436565@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [jupyter/nbviewer] The error was: Failed to connect to localhostport 8988: Connection refused (#895)



Hi @Mespn520 I'm unable to reproduce this error, so I am provisionally closing this issue. If you tried the suggestion I gave above, and it still didn't work, please let me know, and I can reopen the issue.
 
&mdash;
