### ISSUE TITLE
nbviewer error displaying output from IPython.display.Javascript when using lib=

### ISSUE THREAD

**Issue by tony-johnson** [jupyter/nbviewer#836] opened 2019-06-15 07:01 UTC
When executing a trivial Notebook which contains:

`IPython.display.Javascript("""element.append("This is a test");""",lib=["https://cdnjs.cloudflare.com/ajax/libs/d3/5.9.2/d3.min.js"])`

repeated in several consecutive cells, jupyter noteboook correctly displays "This is a test" in each output cell as expected. Viewing the notebook in nbviewer does not behave as expected, and instead displays all the output in the last cell.(See screenshots below)

**To Reproduce**
Go to: https://nbviewer.jupyter.org/url/www.slac.stanford.edu/~tonyj/JavascriptTest.ipynb

**Screenshots**
Notebook rendered in Jupyter: 

![image](https://user-images.githubusercontent.com/11215747/59548044-e583c900-8efd-11e9-91fe-bf07609094b5.png)

Notebook rendered in nbviewer:

![image](https://user-images.githubusercontent.com/11215747/59548055-ff251080-8efd-11e9-82a0-35d499b995f6.png)

**Desktop (please complete the following information):**
 - Linux Ubuntu 19.04 (16 bit)
 - Browser chrome
 - Version 74.0.3729.169 (Official Build) (64-bit)

**Additional context**

I believe the source of the problem is that jupyter generates the following for each cell:

`"application/javascript": [
       "$.getScript(\"https://cdnjs.cloudflare.com/ajax/libs/d3/5.9.2/d3.min.js\", function () {\n",
       "element.append(\"This is a test\");});\n"
      ]`
 
Note the asynchronous execution of the element.append, after the script load.

nbviewer converts this to:

`<script type="text/javascript">
var element = $('#f4bde6d7-91f5-41f5-b818-6e9ebbc3d826');
$.getScript("https://cdnjs.cloudflare.com/ajax/libs/d3/5.9.2/d3.min.js", function () {
element.append("This is a test");});
</script>`

Note the global scope definition of var element.

When several of these cells are present in the python notebook, the asynchronous execution of the element.append picks up the most recent (last) definition of element, instead of the intended definition of element for that cell.

I think a fix would be to create a function(){} for each cell, and define var element inside that function so that it is locally scoped relative to the code in the remainder of the function.

**Comment by krinsman** [comment] 2019-07-05 19:30
This sounds like it might be an NBConvert error (the program NBViewer calls) and not an NBViewer error. Have you tried running `jupyter nbconvert --to html JavaScriptTest.ipynb`? Is the output the same as from Jupyter notebook?

If not, I would recommend opening an issue with [NBConvert](https://github.com/jupyter/nbconvert) instead.

**Comment by krinsman** [comment] 2019-11-21 22:16
@tony-johnson Did you check whether this still happens when running with NBConvert?

It's also possible to open the notebook in classic Jupyter Notebook or JupyterLab, and clicking `Save As` -> `HTML` to run NBConvert to convert the notebook into HTML.

I will tentatively close this issue assuming that the problem is with NBConvert. Please let me know if it should be reopened!

**Closed by krinsman** 2019-11-21 22:16 UTC
Labels: tag:Other Jupyter Project, tag:Upstream, type:Bug
