### ISSUE TITLE
README.ipynb

### ISSUE THREAD

**Issue by TomConlin** [jupyter/nbviewer#498] opened 2015-09-05 19:50 UTC
GH repos have a text or markdown README file that is displayed by default when the repo is visited
extending the acceptable formats for READMEs to include Jupyter notebooks rendered with nbviewer will reduce instruction/documentation necessary for new users of notebooks rendered on GH.

**Comment by bollwyvl** [comment] 2015-09-10 04:19
I have struggled with whether this would be good or not. A repo's readme is a very important document, and should be as portable and accessible as possible... For developers. I think a JSON document is almost too complex for this role. For starters, the mobile gh site doesn't render notebooks at all yet, rendering on desktop takes a couple seconds, and nobody likes editing JSON with a text editor.

On some of my repos, i have a readme.ipynb that i use to drive generation of a readme.md and/or a readme.rst, if i will be publishing to pypi.

We have in the past discussed adopting an index.ipynb convention, which would be rendered along with a folder listing here on nbviewer, but i don't think we'd expect gh to do the same.

**Comment by damianavila** [comment] 2015-09-11 16:46
>I think a JSON document is almost too complex for this role. For starters, the mobile gh site doesn't render notebooks at all yet, rendering on desktop takes a couple seconds, and nobody likes editing JSON with a text editor.

I agree on this view...

**Comment by bollwyvl** [comment] 2015-10-06 18:05
Closing from lack of discussion!

**Closed by bollwyvl** 2015-10-06 18:05 UTC
Labels: github

**Comment by blokeley** [comment] 2017-02-26 16:12
The issue is not dead: https://github.com/github/markup/issues/929

**Comment by josepablog** [comment] 2017-09-27 21:30
i'd love this feature

**Comment by Miladiouss** [comment] 2019-10-15 20:58
It's just that writing equations is not supported in gh markdown. So this would be a good alternative.

**Comment by krinsman** [comment] 2019-10-15 21:11
I don't understand -- wouldn't this be an issue for GitHub, not NBViewer?

GitHub has its own way of rendering notebooks which doesn't use NBViewer anyway, so it seems unlikely that they wouldn't use NBViewer to render _any_ notebook, _except_ for one used as a README.
