### ISSUE TITLE
ERROR: unknown command "download"

### ISSUE THREAD

**Issue by justineuro** [jupyter/nbviewer#786] opened 2018-07-31 11:23 UTC
**Describe the bug**
While following instructions for **Local Installation: Static Assets** the following error occurreed:
```
invoke less --debug
Downloading from pypi -> /home/juro/R+/DataCamp/Jupyter/nbviewer-master/notebook-5.5.0.tar.gz
ERROR: unknown command "download"
```

**To Reproduce**
1. `cd`  <path/to/reposittory>
2. `pip install -r requirements.txt --user`  
or `pip3 install -r requirements.txt --user`  
or `invoke less --debug` after either of the two `pip` steps above

**Expected behavior**
Complete installation of static assets.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Desktop (please complete the following information):**
 - OS: Debian 8 (Jessie) -  Linux 4.9.0-0.bpo.6-686
 - Browser: Mozilla Firefox
 - Version:  Mozilla 5.0 (X11; Linux i686; rv:61.0) Gecko/20100101 Firefox/61.0]

**Additional context**
- `npm` 5.6.0 

Thank you very much in advance for any info on how to repair this error.

**Comment by parente** [comment] 2018-09-01 17:15
@justineuro What version of pip are you using?

**Comment by pelson** [comment] 2018-10-16 00:56
Can you confirm that you've run npm install, and that node_modules is on your PATH (i.e. PATH includes ``./node_modules/.bin``)?

I've just re-setup a development environment from scratch and had no issues (OSX) when following the README, with the exception that I needed to ensure I had a good setup of npm (i.e. the aforementioned path modification).

**Comment by krinsman** [comment] 2020-02-04 19:27
@justineuro Due to the inability to reproduce this error, I am tentatively closing this issue as resolved. Please let me know if that is not the case, so that this issue can be reopened. Thank you for using NBViewer!

**Closed by krinsman** 2020-02-04 19:27 UTC
Labels: status:Needs Reproduction
