### ISSUE TITLE
Parsing bug when starting an equation with `- `

### ISSUE THREAD

**Issue by fredrikekre** [jupyter/nbviewer#767] opened 2018-04-24 07:18 UTC
Consider the following markdown cell in a [notebook](https://gist.githubusercontent.com/fredrikekre/02e0b4936b648770b8040cc1af277e4c/raw/3db45372885d16f79ebcd4de1d88c6514869cda3/mathbug.ipynb):
```
\begin{equation}
- x
\end{equation}
```
This renders incorrectly in [nbviewer](https://nbviewer.jupyter.org/gist/fredrikekre/02e0b4936b648770b8040cc1af277e4c):
![screenshot from 2018-04-24 09-17-28](https://user-images.githubusercontent.com/11698744/39171896-61865db6-47a0-11e8-837a-35a4ea5046a6.png)

but works locally (and in [GitHubs viewer}(https://gist.github.com/fredrikekre/02e0b4936b648770b8040cc1af277e4c)). The minus is interpreted as a markdown bullet.

**Comment by ikkoham** [comment] 2018-06-21 02:51
I found same one...
Related to https://github.com/jupyter/nbconvert/issues/771

**Comment by krinsman** [comment] 2019-11-21 22:28
@fredrikekre 
Can you check to see whether this still happens when running with NBConvert on the notebook?

This sounds like it might be an NBConvert error (the program NBViewer calls). Have you tried running `jupyter nbconvert --to html JavaScriptTest.ipynb`? 

It's also possible to open the notebook in classic Jupyter Notebook or JupyterLab, and clicking `Save As` -> `HTML` to run NBConvert to convert the notebook into HTML.

Is the output the same as from Jupyter notebook/NBViewer? See: https://nbconvert.readthedocs.io/en/latest/usage.html

It might make sense to open an issue with [NBConvert](https://github.com/jupyter/nbconvert) instead.

I will tentatively close this issue assuming that the problem is with NBConvert. Please let me know if it should be reopened!

**Closed by krinsman** 2019-11-21 22:28 UTC
Labels: tag:Upstream, type:Bug
